#!/usr/bin/env python3
# VER-3: renders the Settings page from the firmware's own widget code, so the pictures match
# the device: ESPHome generates the C++ for sky-tracker.yaml (--only-generate), the settings
# page's LVGL calls are lifted out of it, LVGL is built with ESPHome's generated lv_conf.h (its
# theme, its defaults), the fonts are rebuilt from the YAML's font list, and render_settings.cpp
# draws each tab into docs/comps/settings_<tab>.png.
#   ./render_settings.py
import os, re, shutil, subprocess, sys, urllib.parse, urllib.request
from concurrent.futures import ThreadPoolExecutor

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.abspath(os.path.join(HERE, "../.."))
OUT = os.path.join(HERE, "out", "page")
DEPS = os.path.join(HERE, "deps")
ESPHOME = os.path.expanduser("~/.skyenv/bin/esphome")
CC, CXX = os.environ.get("CC", "cc"), os.environ.get("CXX", "c++")


def run(*a, **k):
    subprocess.run(a, check=True, **k)


# ---------------------------------------------------------------- 1. ESPHome's generated code
def generate():
    cfg = os.path.join(OUT, "fw")
    os.makedirs(cfg, exist_ok=True)
    y = open(os.path.join(ROOT, "sky-tracker.yaml"), encoding="utf-8").read()
    y = re.sub(r"  - source:\n      type: git\n      url: https://github.com/akcoder/sky-tracker\n      ref: main\n",
               "  - source:\n      type: local\n      path: " + os.path.join(ROOT, "components") + "\n", y)
    open(os.path.join(cfg, "sky-tracker.yaml"), "w", encoding="utf-8").write(y)
    run(ESPHOME, "compile", "--only-generate", "sky-tracker.yaml", cwd=cfg, stdout=subprocess.DEVNULL)
    return os.path.join(cfg, ".esphome", "build", "sky-tracker", "src")


# ---------------------------------------------------------------- 2. the page's LVGL calls
def extract(src):
    m = open(os.path.join(src, "main.cpp"), encoding="utf-8").read().split("\n")
    s = next(i for i, l in enumerate(m) if "new(settings_page) LvPageType" in l)
    # the page's widgets end where the generated event wiring begins (the settings page is the last one)
    e = next(i for i in range(s + 1, len(m)) if re.search(r"new\(\w+_page\) LvPageType", m[i]) or m[i].lstrip().startswith("new(trigger"))
    body, objs, fonts, wrap = [], set(), set(), set()
    for l in m[s:e]:
        t = l.strip()
        if not t or t.startswith(("//", "#line", "new(")) or "->add_page(" in t:
            continue
        w = re.match(r"(\w+)->set_obj\((lv_\w+_create\(.*\))\);$", t)
        if w:  # an ESPHome wrapper (dropdown): plain LVGL object
            wrap.add(w.group(1))
            t = f"{w.group(1)} = {w.group(2)};"
        w = re.match(r"(\w+)->set_options\(\{(.*)\}\);$", t)
        if w:
            opts = "\\n".join(re.findall(r'"((?:[^"\\]|\\.)*)"', w.group(2)))
            t = f'lv_dropdown_set_options({w.group(1)}, "{opts}");'
        t = t.replace("settings_page->obj", "page")
        for x in wrap:
            t = t.replace(x + "->obj", x)
        if "->" in t or "esphome" in t:
            continue
        a = re.match(r"(\w+) = lv_\w+_create\(", t)
        if a and not t.startswith("lv_obj_t"):
            objs.add(a.group(1))
        f = re.match(r"lv_obj_set_style_text_font\(\w+, (\w+),", t)
        if f:
            fonts.add(f.group(1))
        body.append("  " + t)
    while body and body[-1].strip() == "{":  # the next section's block opens just before the end marker
        body.pop()
    decl = [f"static lv_obj_t *{o};" for o in sorted(objs)]
    decl += [f"extern \"C\" const lv_font_t gen_{f};\nstatic const lv_font_t *const {f} = &gen_{f};" for f in sorted(fonts)]
    open(os.path.join(OUT, "settings_gen.inc"), "w").write(
        "// generated by render_settings.py from ESPHome's main.cpp: the settings page\n"
        + "\n".join(decl) + "\nstatic void build_settings(lv_obj_t *page) {\n" + "\n".join(body) + "\n}\n")
    return fonts


# ---------------------------------------------------------------- 3. the fonts, from the YAML
def gfont(spec):  # "Roboto Mono@500" -> a static TTF from Google Fonts (as ESPHome's gfonts://)
    fam, _, wt = spec.partition("@")
    wt = wt or "400"
    dst = os.path.join(DEPS, "gfonts", f"{fam.replace(' ', '')}-{wt}.ttf")
    if not os.path.exists(dst):
        os.makedirs(os.path.dirname(dst), exist_ok=True)
        css = urllib.request.urlopen(urllib.request.Request(
            f"https://fonts.googleapis.com/css2?family={urllib.parse.quote(fam)}:wght@{wt}",
            headers={"User-Agent": "Mozilla/4.0"})).read().decode()  # an old browser gets TTF
        urllib.request.urlretrieve(re.search(r"url\((\S+?\.ttf)\)", css).group(1), dst)
    return dst


def fonts_from_yaml(want):
    y = open(os.path.join(ROOT, "sky-tracker.yaml"), encoding="utf-8").read()
    sec = y[y.index("\nfont:\n"):]
    sec = sec[:re.search(r"\n[a-z_]+:\n", sec[1:]).start() + 1]
    anchors = {}
    for name, val in re.findall(r"&(\w+) (\".*\"|\[.*\])", sec):
        anchors[name] = val
    jobs = []
    for ent in re.split(r"\n  - file:", sec)[1:]:
        fid = re.search(r"\n    id: (\w+)", ent).group(1)
        if fid not in want:
            continue
        size = re.search(r"\n    size: (\d+)", ent).group(1)
        bpp = (re.search(r"\n    bpp: (\d+)", ent) or [None, "1"])[1]
        g = re.search(r"\n    glyphs: (?:&\w+ )?(\*\w+|\".*\"|\[.*\])", ent).group(1)
        g = anchors[g[1:]] if g.startswith("*") else g
        gf = re.search(r'"gfonts://([^"]+)"', ent)
        ttf = gfont(gf.group(1)) if gf else os.path.join(DEPS, "materialdesignicons-webfont.ttf")
        args = ["--font", ttf]
        if g.startswith("["):
            args += ["-r", ",".join("0x" + c for c in re.findall(r"U000(F[0-9A-F]{4})", g))]
        else:
            txt = bytes(g[1:-1], "utf-8").decode("unicode_escape").encode("latin-1").decode("utf-8")
            args += ["--symbols", txt]
        out = os.path.join(OUT, f"font_{fid}.c")
        jobs.append(["npx", "--yes", "lv_font_conv", *args, "--size", size, "--bpp", bpp, "--format", "lvgl",
                     "--no-compress", "--lv-font-name", "gen_" + fid, "-o", out])
    with ThreadPoolExecutor(4) as ex:
        list(ex.map(lambda j: run(*j, stdout=subprocess.DEVNULL), jobs))
    return [os.path.join(OUT, f"font_{f}.c") for f in sorted(want)]


# ---------------------------------------------------------------- 4. LVGL with the device's lv_conf.h
def lvgl(src):
    conf = open(os.path.join(src, "lv_conf.h")).read()
    conf = conf.replace("LV_STDLIB_CUSTOM", "LV_STDLIB_CLIB")  # ESPHome's PSRAM allocator: plain malloc here
    cdir = os.path.join(OUT, "conf")
    os.makedirs(cdir, exist_ok=True)
    path = os.path.join(cdir, "lv_conf.h")
    lib = os.path.join(OUT, "liblvgl_esp.a")
    if not os.path.exists(path) or open(path).read() != conf or not os.path.exists(lib):
        open(path, "w").write(conf)
        objd = os.path.join(OUT, "lvobj")
        shutil.rmtree(objd, ignore_errors=True)
        os.makedirs(objd)
        srcs = [os.path.join(d, f) for d, _, fs in os.walk(os.path.join(DEPS, "lvgl", "src")) for f in fs if f.endswith(".c")]
        def comp(c):
            o = os.path.join(objd, c.replace("/", "_") + ".o")
            run(CC, "-O2", "-w", "-DLV_CONF_INCLUDE_SIMPLE", "-I" + cdir, "-I" + DEPS, "-I" + os.path.join(DEPS, "lvgl"),
                "-c", c, "-o", o)
            return o
        with ThreadPoolExecutor(8) as ex:
            objs = list(ex.map(comp, srcs))
        if os.path.exists(lib):
            os.remove(lib)
        run("ar", "rcs", lib, *objs)
    return cdir, lib


def main():
    os.makedirs(OUT, exist_ok=True)
    print("generating the firmware's code...")
    src = generate()
    fonts = extract(src)
    print("page fonts:", ", ".join(sorted(fonts)))
    fc = fonts_from_yaml(fonts)
    print("LVGL with the device's lv_conf.h...")
    cdir, lib = lvgl(src)
    fo = []
    for c in fc:  # as C: a const at namespace scope in C++ would not be visible to the linker
        o = c[:-2] + ".o"
        run(CC, "-O2", "-w", "-DLV_CONF_INCLUDE_SIMPLE", "-DLV_LVGL_H_INCLUDE_SIMPLE", "-I" + cdir, "-I" + os.path.join(DEPS, "lvgl"),
            "-c", c, "-o", o)
        fo.append(o)
    exe = os.path.join(OUT, "render_settings")
    run(CXX, "-std=gnu++20", "-O2", "-w", "-DLV_CONF_INCLUDE_SIMPLE", "-I" + cdir, "-I" + DEPS, "-I" + os.path.join(DEPS, "lvgl"),
        "-I" + OUT, "-I" + os.path.join(ROOT, "components", "sky_tracker"), os.path.join(HERE, "render_settings.cpp"),
        *fo, lib, "-lm", "-o", exe)
    run(exe, OUT)
    from PIL import Image
    for t in ("display", "display_tz_open", "location", "celestial", "satellites", "alerts"):
        Image.open(os.path.join(OUT, f"settings_{t}.ppm")).save(os.path.join(ROOT, "docs", "comps", f"settings_{t}.png"))
    print("docs/comps/settings_*.png written")


if __name__ == "__main__":
    main()
