# Builds sky_stars.h from d3-celestial 0.7.35 data (BSD-3-Clause; Hipparcos positions,
# Stellarium-derived constellation figures). Output: stars to MAG_LIMIT plus every star
# a figure line touches, figures as index polylines, and label points for names.
import json, math
D='package/data/'
MAG_LIMIT=3.5
# UI-21: figures drawn more prominently (the best-known seven from Alaska)
MAJOR=['UMa','UMi','Cas','Ori','Cyg','Leo','Tau']
stars=json.load(open(D+'stars.6.json'))['features']
lines=json.load(open(D+'constellations.lines.json'))['features']
cons=json.load(open(D+'constellations.json'))['features']
def key(ra,dec): return (round(ra,2), round(dec,2))
bypos={}
for s in stars:
    ra,dec=s['geometry']['coordinates']; ra%=360
    bypos.setdefault(key(ra,dec), s)
def near(ra,dec):
    k=key(ra%360,dec)
    if k in bypos: return bypos[k]
    best=None;bd=1e9
    for s in stars:
        r,d=s['geometry']['coordinates']
        dd=((r-ra+180)%360-180)**2*math.cos(math.radians(dec))**2+(d-dec)**2
        if dd<bd: bd=dd;best=s
    return best if bd<0.01**2*4 else None
out=[]; idx={}
def add(ra,dec,mag,hip):
    k=('h',hip) if hip is not None else ('p',round(ra,3),round(dec,3))
    if k in idx: return idx[k]
    idx[k]=len(out); out.append((ra%360,dec,mag)); return idx[k]
for s in sorted(stars,key=lambda s:s['properties']['mag']):
    if s['properties']['mag']<=MAG_LIMIT:
        ra,dec=s['geometry']['coordinates']; add(ra,dec,s['properties']['mag'],s['id'])
polys=[]; unmatched=0; major_polys=[]
for f in lines:
    for pl in f['geometry']['coordinates']:
        if f['id'] in MAJOR: major_polys.append(len(polys))
        seq=[]
        for ra,dec in pl:
            s=near(ra,dec)
            if s: seq.append(add(s['geometry']['coordinates'][0],s['geometry']['coordinates'][1],s['properties']['mag'],s['id']))
            else: unmatched+=1; seq.append(add(ra,dec,9.9,None))
        polys.append(seq)
names=[]
for c in cons:
    p=c['properties']; ra,dec=c['geometry']['coordinates']
    nm=p['name'].replace('Serpens Caput','Serpens').replace('Serpens Cauda','Serpens').replace('\u00f6','o').replace('ö','o')
    names.append((nm, int(p['rank']), ra%360, dec))
H=[]
H.append('// sky_stars.h — generated by gen_stars.py; do not edit.')
H.append('// Source: d3-celestial 0.7.35 data (BSD-3-Clause), J2000 positions.')
H.append(f'// {len(out)} stars (mag <= {MAG_LIMIT} plus figure vertices), {len(polys)} figure polylines, {len(names)} names.')
H.append('#pragma once\n#include <cstdint>\nnamespace sat {\nnamespace sky {')
H.append('struct Star { uint16_t ra; int16_t dec; int8_t mag10; };  // ra: 65536 = 360°, dec: 32767 = 90°, mag x10')
H.append(f'constexpr int N_STARS = {len(out)};')
H.append('const Star STARS[N_STARS] = {')
row=[]
for ra,dec,mag in out:
    row.append('{%d,%d,%d}'%(round(ra/360*65536)%65536, round(dec/90*32767), max(-15,min(99,round(mag*10)))))
for i in range(0,len(row),8): H.append('  '+','.join(row[i:i+8])+',')
H.append('};')
flat=[]
for p in polys: flat.append(len(p)); flat+=p
H.append('// polylines: count, then that many star indices; repeated')
H.append(f'constexpr int N_FIG = {len(flat)};')
H.append('const uint16_t FIG[N_FIG] = {')
for i in range(0,len(flat),16): H.append('  '+','.join(map(str,flat[i:i+16]))+',')
H.append('};')
H.append('// polylines (in FIG order) belonging to the major constellations: '+', '.join(MAJOR))
H.append(f'constexpr int N_FIG_MAJOR = {len(major_polys)};')
H.append('const uint8_t FIG_MAJOR[N_FIG_MAJOR] = {'+','.join(map(str,major_polys))+'};')
H.append('struct Name { const char *text; uint8_t rank; uint16_t ra; int16_t dec; };  // rank 1 major .. 3 minor')
H.append(f'constexpr int N_NAMES = {len(names)};')
H.append('const Name NAMES[N_NAMES] = {')
for n,r,ra,dec in names:
    H.append('  {"%s",%d,%d,%d},'%(n,r,round(ra/360*65536)%65536,round(dec/90*32767)))
H.append('};\n}  // namespace sky\n}  // namespace sat')
open('/home/claude/sky/sky_stars.h','w').write('\n'.join(H)+'\n')
print(len(out),'stars', sum(1 for s in out if s[2]<=MAG_LIMIT),'bright', len(polys),'polys',len(flat),'fig entries','unmatched',unmatched)
print('bytes ~', len(out)*6+len(flat)*2+sum(len(n[0])+1+8 for n in names))
