#!/usr/bin/env python3
"""UI-65: render sky_logo.svg to sky_logo.h (LVGL RGB565A8, LOGO_PX square). Needs cairosvg, Pillow."""
import io, sys, cairosvg
from PIL import Image
N = int(sys.argv[1]) if len(sys.argv) > 1 else 200
im = Image.open(io.BytesIO(cairosvg.svg2png(url='sky_logo.svg', output_width=N, output_height=N))).convert('RGBA')
px = im.load()
rgb, a = bytearray(), bytearray()
for y in range(N):
    for x in range(N):
        r, g, b, al = px[x, y]
        v = ((r >> 3) << 11) | ((g >> 2) << 5) | (b >> 3)
        rgb += bytes([v & 255, v >> 8]); a.append(al)
data = bytes(rgb + a)
import zlib, base64
co = zlib.compressobj(9, zlib.DEFLATED, -15)  # raw deflate: the ROM's tinfl inflates it at boot
z = co.compress(data) + co.flush()
b64 = base64.b64encode(z).decode()
rows = ['    "' + b64[i:i + 100] + '"' for i in range(0, len(b64), 100)]
open('sky_logo.h', 'w').write(f'''#pragma once
// UI-65: the Sky Tracker logo (sky_logo.svg: the web page's header logo, NET-10a, redrawn
// with more detail for large sizes), {N}x{N} LVGL RGB565A8 (an RGB565 plane, then an
// 8-bit alpha plane: {len(data)} bytes), raw-deflated ({len(z)} bytes) and base64'd.
// Inflated once into PSRAM (sky_about.h). Generated by tools/gen_logo.py.
#ifdef SKY_IMPL  // only sky_extra.cpp needs the bytes
namespace sat {{
constexpr int LOGO_PX = {N};
constexpr unsigned LOGO_RAW = {len(data)};
inline const char LOGO_B64[] =
''' + '\n'.join(rows) + ''';
}  // namespace sat
#endif
''')
print(N, len(data), len(z), len(b64))
