# Builds sky_cfig.h: a 40 px stick figure per constellation (UI-46a), in sky::NAMES order.
# Gnomonic projection about the figure's centre, north up, east left (as seen looking up),
# scaled to fit 34 px. Bytes per figure: npoly, then per polyline n, then n x (x, y, size).
import json, math
D='package/data/'
L={l['id']:l for l in json.load(open(D+'constellations.lines.json'))['features']}
C=json.load(open(D+'constellations.json'))['features']
stars=json.load(open(D+'stars.6.json'))['features']
bypos={}
for s in stars:
    ra,dec=s['geometry']['coordinates']; bypos[(round(ra%360,2),round(dec,2))]=s['properties']['mag']
def mag(ra,dec):
    k=(round(ra%360,2),round(dec,2))
    if k in bypos: return bypos[k]
    best=9.9;bd=1e9
    for s in stars:
        r,d=s['geometry']['coordinates']
        dd=((r-ra+180)%360-180)**2*math.cos(math.radians(dec))**2+(d-dec)**2
        if dd<bd: bd=dd;best=s['properties']['mag']
    return best if bd<0.0004 else 9.9
def vec(ra,dec):
    r,d=math.radians(ra),math.radians(dec); return (math.cos(d)*math.cos(r),math.cos(d)*math.sin(r),math.sin(d))
SIZE=40; FIT=34
blob=[]; offs=[]; figs={}
for c in C:
    polys=L[c['id']]['geometry']['coordinates']
    pts=[p for pl in polys for p in pl]
    vs=[vec(*p) for p in pts]
    cx=sum(v[0] for v in vs); cy=sum(v[1] for v in vs); cz=sum(v[2] for v in vs); n=math.sqrt(cx*cx+cy*cy+cz*cz)
    c0=(cx/n,cy/n,cz/n)
    e=(-c0[1],c0[0],0.0); en=math.hypot(e[0],e[1])
    e=(e[0]/en,e[1]/en,0) if en>1e-9 else (0,1,0)
    nn=(c0[1]*e[2]-c0[2]*e[1], c0[2]*e[0]-c0[0]*e[2], c0[0]*e[1]-c0[1]*e[0])
    def proj(p):
        v=vec(*p); w=sum(a*b for a,b in zip(v,c0))
        return (-sum(a*b for a,b in zip(v,e))/w, -sum(a*b for a,b in zip(v,nn))/w)
    P=[[proj(p) for p in pl] for pl in polys]
    xs=[x for pl in P for x,_ in pl]; ys=[y for pl in P for _,y in pl]
    span=max(max(xs)-min(xs),max(ys)-min(ys),1e-6); k=FIT/span
    mx=(max(xs)+min(xs))/2; my=(max(ys)+min(ys))/2
    out=[len(P)]
    for pl,raw in zip(P,polys):
        out.append(len(pl))
        for (x,y),(ra,dec) in zip(pl,raw):
            m=mag(ra,dec); sz=2 if m<1.5 else 1 if m<3.2 else 0
            out += [max(0,min(SIZE-1,round(SIZE/2+(x-mx)*k))), max(0,min(SIZE-1,round(SIZE/2+(y-my)*k))), sz]
    offs.append(len(blob)); blob+=out; figs[c['id']]=(P,out)
offs.append(len(blob))
H=['// sky_cfig.h — generated by gen_cfig.py; do not edit.',
   '// d3-celestial 0.7.35 figures (BSD-3-Clause). One 40 px stick figure per sky::NAMES entry:',
   '// npoly, then per polyline: n, then n x (x, y, size 0..2). North up, east left.',
   '#pragma once\n#include <cstdint>\nnamespace sat {\nnamespace sky {',
   f'constexpr int CFIG_PX = {SIZE};',
   f'const uint16_t CFIG_OFF[{len(offs)}] = {{'+','.join(map(str,offs))+'};',
   f'const uint8_t CFIG[{len(blob)}] = {{']
for i in range(0,len(blob),24): H.append('  '+','.join(map(str,blob[i:i+24]))+',')
H.append('};\n}  // namespace sky\n}  // namespace sat')
open('/home/claude/sky/sky_cfig.h','w').write('\n'.join(H)+'\n')
print(len(blob),'bytes')
# preview sheet
from PIL import Image, ImageDraw
S=3; img=Image.new('RGB',(10*48*S,9*48*S),(16,27,61)); d=ImageDraw.Draw(img)
for i,c in enumerate(C):
    ox=(i%10)*48*S+4*S; oy=(i//10)*48*S+4*S; b=figs[c['id']][1]; j=1
    for _ in range(b[0]):
        n=b[j]; j+=1; pts=[(b[j+3*q],b[j+3*q+1],b[j+3*q+2]) for q in range(n)]; j+=3*n
        d.line([(ox+x*S,oy+y*S) for x,y,_ in pts],fill=(127,150,215),width=S)
        for x,y,s in pts:
            r=(0.8+0.6*s)*S; d.ellipse([ox+x*S-r,oy+y*S-r,ox+x*S+r,oy+y*S+r],fill=(240,244,255))
img.save('/tmp/claude-0/cfig_sheet.png')
print([c['id'] for c in C][:12])
